FROM node:20-alpine AS builder
WORKDIR /app
ENV NEXT_PUBLIC_API_URL=https://api.citeflow.cn
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD npx next start -p ${PORT:-3000}
