"""CiteFlow public API — Probe → Analyst → Doctor pipeline (no auth/payment required)."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.analyst.analyst_context import build_context
from agents.analyst.analyst_rules import detect_rules
from agents.knowledge_loader import get_prescription_knowledge


def run_pipeline(domain: str, brand_name: str, industry: str = "", competitors: list[str] = None) -> dict:
    """Run Probe → Analyst → Doctor pipeline.

    This is a demo entry point that expects probe_output.json to already exist
    (generated by running a full Probe scan). For production use, connect the
    full agent pipeline in agents/probe/probe_node.py.

    Args:
        domain: Brand website domain (e.g. "pela.com")
        brand_name: Brand name (e.g. "Pela Case")
        industry: Industry category (optional)
        competitors: List of competitor brand names (optional)

    Returns:
        dict with probe_output, analyst_output, doctor_output
    """
    # Load pre-generated probe output (in production, run agents.probe.probe_node)
    probe_path = os.path.join(os.path.dirname(__file__), "..", "examples", "sample_probe_output.json")
    if os.path.exists(probe_path):
        with open(probe_path) as f:
            probe_output = json.load(f)
    else:
        raise FileNotFoundError(
            f"Probe output not found at {probe_path}. "
            "Run a full Probe scan first or use examples/sample_probe_output.json."
        )

    # Analyst
    ctx = build_context(probe_output)
    rules = detect_rules(ctx)
    triggered = rules.get("triggered", [])
    print(f"Analyst: {len(triggered)} rules triggered")
    for r in triggered:
        print(f"  R{r['rule_id']}: {r['name']} ({r['severity']}) — {r['evidence']}")

    # Doctor (knowledge injection only — full LLM call requires API key)
    knowledge = get_prescription_knowledge(triggered)
    print(f"Doctor: knowledge injection ready ({len(knowledge)} chars)")

    return {
        "probe_output": probe_output,
        "analyst_rules": rules,
        "knowledge": knowledge,
    }


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="CiteFlow — Brand AI Search Diagnostic")
    parser.add_argument("--domain", required=True, help="Brand website domain")
    parser.add_argument("--brand", required=True, help="Brand name")
    parser.add_argument("--industry", default="", help="Industry category")
    parser.add_argument("--competitors", nargs="*", default=[], help="Competitor brand names")
    args = parser.parse_args()

    result = run_pipeline(args.domain, args.brand, args.industry, args.competitors)
    print(f"\nDone. {len(result['analyst_rules'].get('triggered', []))} rules triggered.")
